export const authConstant = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  LOG_OUT: "LOG_OUT",
  KEEP_LOGIN: "KEEP_LOGIN",
};

export const productsConstant = {
  GET_PRODUCTS_REQUEST: "GET_PRODUCTS_REQUEST",
  GET_PRODUCTS_FAILURE: "GET_PRODUCTS_FAILURE",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",

  ADD_PRODUCTS_REQUEST: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCTS_FAILURE: "ADD_PRODUCTS_FAILURE",
  ADD_PRODUCTS_SUCCESS: "ADD_PRODUCTS_SUCCESS",

  UPDATE_PRODUCTS_REQUEST: "UPDATE_PRODUCT_REQUEST",
  UPDATE_PRODUCTS_FAILURE: "UPDATE_PRODUCTS_FAILURE",
  UPDATE_PRODUCTS_SUCCESS: "UPDATE_PRODUCTS_SUCCESS",

  DELETE_PRODUCTS_REQUEST: "DELETE_PRODUCT_REQUEST",
  DELETE_PRODUCTS_FAILURE: "DELETE_PRODUCTS_FAILURE",
  DELETE_PRODUCTS_SUCCESS: "DELETE_PRODUCTS_SUCCESS",

  GET_TOP_SALE_REQUEST: "GET_TOP_SALE_REQUEST",
  GET_TOP_SALE_FAILURE: "GET_TOP_SALE_FAILURE",
  GET_TOP_SALE_SUCCESS: "GET_TOP_SALE_SUCCESS",

  GET_POP_TAG_REQUEST: "GET_POP_TAG_REQUEST",
  GET_POP_TAG_FAILURE: "GET_POP_TAG_FAILURE",
  GET_POP_TAG_SUCCESS: "GET_POP_TAG_SUCCESS",
};

export const ordersConstant = {
  GET_ORDERS_REQUEST: "GET_ORDERS_REQUEST",
  GET_ORDERS_FAILURE: "GET_ORDERS_FAILURE",
  GET_ORDERS_SUCCESS: "GET_ORDERS_SUCCESS",

  SET_SELECTED_ORDER_REQUEST: "SET_SELECTED_ORDER_REQUEST",
  SET_SELECTED_ORDER_SUCCESS: "SET_SELECTED_ORDER_SUCCESS",
  SET_SELECTED_ORDER_FAILURE: "SET_SELECTED_ORDER_FAILURE",

  UPDATE_ORDERS_REQUEST: "UPDATE_ORDERS_REQUEST",
  UPDATE_ORDERS_FAILURE: "UPDATE_ORDERS_FAILURE",
  UPDATE_ORDERS_SUCCESS: "UPDATE_ORDERS_SUCCESS",
};
