export const authConstant = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  LOG_OUT: "LOG_OUT",
  KEEP_LOGIN: "KEEP_LOGIN",
};

export const productsConstant = {
  GET_PRODUCTS_REQUEST: "GET_PRODUCTS_REQUEST",
  GET_PRODUCTS_FAILURE: "GET_PRODUCTS_FAILURE",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",

  ADD_PRODUCTS_REQUEST: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCTS_FAILURE: "ADD_PRODUCTS_FAILURE",
  ADD_PRODUCTS_SUCCESS: "ADD_PRODUCTS_SUCCESS",

  UPDATE_PRODUCTS_REQUEST: "UPDATE_PRODUCT_REQUEST",
  UPDATE_PRODUCTS_FAILURE: "UPDATE_PRODUCTS_FAILURE",
  UPDATE_PRODUCTS_SUCCESS: "UPDATE_PRODUCTS_SUCCESS",

  DELETE_PRODUCTS_REQUEST: "DELETE_PRODUCT_REQUEST",
  DELETE_PRODUCTS_FAILURE: "DELETE_PRODUCTS_FAILURE",
  DELETE_PRODUCTS_SUCCESS: "DELETE_PRODUCTS_SUCCESS",
};
